notify:
  email:
    recipients:
      - juan.baptiste@gmail.com
    from: $$SMTP_FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
  downstream:
    server: $$DOWNSTREAM_DRONE_SERVER
    repositories:
      - jbaptiste_cs/ctecsas-backup

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/otrs
    tag:
      - latest
    file: Dockerfile
    context:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
